# Generated by Django 5.0.4 on 2025-08-07 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandCategory',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('sgg_oid', models.IntegerField()),
                ('jibun', models.CharField(blank=True, max_length=255, null=True)),
                ('bchk', models.CharField(blank=True, max_length=255, null=True)),
                ('pnu', models.CharField(blank=True, max_length=255, null=True)),
                ('col_adm_se', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('region', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filter"."jimok',
                'managed': False,
            },
        ),
    ]
